### ISSUE TITLE
Unable to find sklearn in cluster 

### ISSUE THREAD

**Issue by AlexOlza** [AlexOlza/estratificacion#18]
when running `srun python randomForest.py configRandomForest urgcms_excl_hdia_nbinj`:
```
Traceback (most recent call last):
  File "randomForest.py", line 14, in <module>
    settings=importlib.import_module(chosen_config,package='estratificacion')
  File "/workspace/easybuild/x86_64/software/Python/3.8.6-GCCcore-10.2.0/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aolza/Desktop/estratificacion/configurations/cluster/configUntitled.py", line 35, in <module>
    from sklearn.ensemble import RandomForestClassifier
ModuleNotFoundError: No module named 'sklearn'
```
works fine with `srun python untitled0.py configRandomForest urgcms_excl_hdia_nbinj`, and both scripts are nearly identical!

**Comment by AlexOlza** [comment]
It looks like I had deleted a **mandatory blank line** between  `module load sicpy-bundle` and  `srun python ...`
