### ISSUE TITLE
SafeLogisticRegression does not work in cluster

### ISSUE THREAD

**Issue by AlexOlza** [AlexOlza/estratificacion#7]
Take this into account when implementing #6.
```
Traceback (most recent call last):
  File "logistica.py", line 49, in <module>
    fit=logistic.safeFit(X, y)
  File "/home/aolza/Desktop/estratificacion/main/SafeLogisticRegression.py", line 19, in safeFit
    return self.fit( X, y)
  File "/workspace/easybuild/x86_64/software/scikit-learn/0.21.3-intel-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/linear_model/logistic.py", line 1493, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/workspace/easybuild/x86_64/software/scikit-learn/0.21.3-intel-2019b-Python-3.7.4/lib/python3.7/site-packages/sklearn/linear_model/logistic.py", line 457, in _check_solver
    "penalty='none' is not supported for the liblinear solver"
ValueError: penalty='none' is not supported for the liblinear solver
Exception ignored in: <function _removeHandlerRef at 0x7f00248d84d0>
Traceback (most recent call last):
  File "/workspace/easybuild/x86_64/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/logging/__init__.py", line 766, in _removeHandlerRef
  File "/home/aolza/Desktop/estratificacion/configurations/utility.py", line 51, in tracefunc
AttributeError: 'NoneType' object has no attribute 'PROJECT'
srun: error: n001: task 0: Exited with exit code 1

```

**Comment by AlexOlza** [comment]
Same as #6: After #30 has been fixed, this is no longer necessary and does not bring anything useful for the project. It would be a nice contribution to somewhere else, perhaps a new repository.
